apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agentic-platform
resources: [cubecluster.yaml]
configMapGenerator:
  - name: agentic-cube-model
    files:
      - AgentMessages.yml=model/AgentMessages.yml
      - AgentRegistrations.yml=model/AgentRegistrations.yml
generatorOptions:
  disableNameSuffixHash: true
