gatewayAPI:
  hostNetwork:
    enabled: true

envoy:
  securityContext:
    capabilities:
      envoy:
        - NET_ADMIN
        - SYS_ADMIN
        - NET_BIND_SERVICE
      keepCapNetBindService: true
